export const news = {
  health: [
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
  ],
  politic: [
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
  ],
  technology: [
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
    {
      id: "",
      title: "",
      content: "",
      imageUri: "",
      newsPath: "",
    },
  ],
};
